# Generated by Django 4.2.6 on 2023-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='overall_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
