basePath: /api/
definitions:
  views.CreateRatingInput:
    properties:
      rate:
        type: integer
      rated_username:
        type: string
    required:
    - rated_username
    type: object
  views.CreateUserRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  views.UserLoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  views.UserOutput:
    properties:
      average_rate:
        type: number
      created_at:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      picture_path:
        type: string
      rank:
        type: integer
      role:
        type: string
      total_raters:
        type: integer
      user_id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server RatingApp server.
  title: Swagger Example API
  version: "1"
paths:
  /chart/list/{username}:
    get:
      consumes:
      - application/json
      description: Get chart details
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Chart details
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get chart details
      tags:
      - Chart
  /picture/upload:
    post:
      consumes:
      - application/json
      description: Upload picture
      parameters:
      - description: Picture
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Picture uploaded
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Upload picture
      tags:
      - Picture
  /rating/create:
    post:
      consumes:
      - application/json
      description: Create a new rating
      parameters:
      - description: Rating
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/views.CreateRatingInput'
      produces:
      - application/json
      responses:
        "200":
          description: Rating created
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Create a new rating
      tags:
      - Rating
  /rating/list:
    get:
      consumes:
      - application/json
      description: Get ratings
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Per page
        in: query
        name: per_page
        type: integer
      - description: Order by
        in: query
        name: order_by
        type: string
      - description: Order
        in: query
        name: order
        type: string
      - description: Rater username
        in: query
        name: rater_username
        type: string
      - description: Rated username
        in: query
        name: rated_username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ratings
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get ratings
      tags:
      - Rating
  /users/{username}:
    get:
      description: Get the details of a user.
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User details" {int} rank "User rank
          schema:
            $ref: '#/definitions/views.UserOutput'
        "404":
          description: User not found
          schema:
            type: string
      summary: Get user details
      tags:
      - Users
  /users/list:
    get:
      description: Get a list of users.
      parameters:
      - description: Order by
        in: query
        name: order_by
        type: string
      - description: Order
        in: query
        name: order
        type: string
      - description: Text
        in: query
        name: text
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      - description: Per page
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Users
          schema:
            type: string
      summary: Get user list
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      description: Log in a user with username and password.
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/views.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User logged in
          schema:
            type: string
      summary: User login
      tags:
      - Authentication
  /users/logout:
    get:
      description: Log out the current user.
      produces:
      - application/json
      responses:
        "200":
          description: User logged out
          schema:
            type: string
      summary: User logout
      tags:
      - Authentication
  /users/signup:
    post:
      consumes:
      - application/json
      description: Register a new user account with a username and password.
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/views.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User created
          schema:
            type: string
      summary: Create a new user account
      tags:
      - Authentication
  /users/validate:
    get:
      description: Check if the user is logged in and the session is valid.
      produces:
      - application/json
      responses:
        "200":
          description: User logged in" {string} string "User role
          schema:
            type: string
      summary: Validate user session
      tags:
      - Authentication
swagger: "2.0"
